#!/usr/bin/env python3
"""
Generate fastabx-compatible item file for Japanese pitch accent ABX (TTS, clipped).

- CLIPPED mode only
- No annotation JSON
- Items are generated by scanning all .wav files under AUDIO_ROOT
- Filename logic is identical in abstraction; only slot positions differ

Expected filename format:
  あつい_厚い_43_A.wav

Slot mapping (logic preserved):
  - speaker        := parts[3]  (A)
  - label (int)    := parts[2]  (43)
  - seq base       := parts[0]  (あつい)
  - context_id     := (label - 1) // 2
  - phone_sequence := f"{seq_base}_{context_id}"
"""

from __future__ import annotations

import argparse
import csv
import wave
from pathlib import Path

# ============================================================
# Hardcoded paths (minimal change)
# ============================================================

AUDIO_ROOT = Path("/home/sunhaitong/ABX_syn/data/standard_Japanese_accent")
OUTPUT_DIR = Path("/home/sunhaitong/fastabx/abx_items/pitch_accent_syn")

# ============================================================
# Filename parsing (logic preserved, slots changed)
# ============================================================

def parse_filename(fname: str):
    """
    Parse filename like あつい_厚い_43_A.wav

    Logical equivalence to:
      S007_87_きって_切手.wav
    """
    stem = Path(fname).stem
    parts = stem.split("_")
    if len(parts) != 4:
        raise ValueError(f"Unexpected filename format: {fname}")

    seq_base = parts[0]     # あつい
    # kanji = parts[1]      # 厚い (unused)
    label = parts[2]        # 43
    speaker = parts[3]      # A

    try:
        utt_num = int(label)
    except ValueError:
        raise ValueError(
            f"Label (part 3 of filename) must be an integer, got '{label}' in {fname}"
        )

    context_id = (utt_num - 1) // 2
    seq = f"{seq_base}_{context_id}"

    return speaker, label, seq, stem


# ============================================================
# Audio utilities
# ============================================================

def get_duration_seconds(audio_path: Path) -> float:
    with wave.open(str(audio_path), "rb") as wf:
        return wf.getnframes() / wf.getframerate()


# ============================================================
# Item construction (annotation-free, clipped)
# ============================================================

def build_items_from_wavs(audio_root: Path) -> list[dict]:
    items: list[dict] = []
    skipped_badname = 0

    for wav_path in sorted(audio_root.rglob("*.wav")):
        try:
            speaker, label, seq, stem = parse_filename(wav_path.name)
        except ValueError as e:
            print(f"Skip (filename): {e}")
            skipped_badname += 1
            continue

        duration = get_duration_seconds(wav_path)

        # #file must be relative to audio_root, without extension
        rel_stem = wav_path.relative_to(audio_root).with_suffix("")

        items.append(
            {
                "#file": str(rel_stem),
                "onset": 0.0,
                "offset": duration,
                "phone_sequence": seq,
                "accent_pattern": label,
                "speaker": speaker,
            }
        )

    if skipped_badname > 0:
        print(f"Skipped {skipped_badname} files due to unexpected filename format")

    return items


# ============================================================
# CSV writer (unchanged)
# ============================================================

def write_items(items: list[dict], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    header = [
        "#file",
        "onset",
        "offset",
        "phone_sequence",
        "accent_pattern",
        "speaker",
    ]
    with output_path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=header)
        writer.writeheader()
        for item in items:
            writer.writerow(item)


# ============================================================
# Main
# ============================================================

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate fastabx item file for Japanese pitch accent ABX (TTS, clipped)"
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=OUTPUT_DIR,
        help="Output directory (default: abx_items/pitch_accent_tts)",
    )
    args = parser.parse_args()

    output_dir = args.output_dir

    print("Mode: clipped (TTS, annotation-free)")
    print(f"Audio root: {AUDIO_ROOT}")
    print(f"Output directory: {output_dir}")
    print()

    items = build_items_from_wavs(AUDIO_ROOT)

    output_path = output_dir / "items.csv"
    write_items(items, output_path)

    # Write audio path for extract_features.py
    with (output_dir / "audio_path.txt").open("w") as f:
        f.write(str(AUDIO_ROOT))

    print(f"\nWrote {len(items)} items to {output_path}")
    print(f"Unique speakers: {len({i['speaker'] for i in items})}")
    print(f"Unique phone sequences: {len({i['phone_sequence'] for i in items})}")
    print(f"Unique accent patterns: {len({i['accent_pattern'] for i in items})}")


if __name__ == "__main__":
    main()
